/**
 * This file was automatically generated by Modelarium
 * on 2020-08-27T14:18:19+00:00
 */

import * as components from "./index";

export default [
    {
        path: "/user",
        name: "UserList",
        component: components.UserList,
    },
    {
        path: "/user/:id?/edit",
        name: "UserEdit",
        component: components.UserEdit,
    },
    {
        path: "/user/table",
        name: "UserTable",
        component: components.UserTable,
    },
    {
        path: "/user/:id",
        name: "UserShow",
        component: components.UserShow,
    },
];
