<?php

/**
 * This file was automatically generated by Modelarium.
 */
class DatabaseSeeder extends Illuminate\Database\Seeder
{
    /**
     * Seed the application\'s database.
     * @return void
     */
    public function run()
    {
        $this->call(PostSeeder::class);
    }
}
