<?php declare(strict_types=1);
/**
 * This file was automatically generated by Modelarium on {{date}}
 */

use Illuminate\Database\Seeder;

class PostSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        factory(App\Models\Post::class)->create();
    }
}
