<?php
/**
 * This file was automatically generated by Modelarium on {{date}}
 */

/** @var \Illuminate\Database\Eloquent\Factory $factory */
use Faker\Generator as Faker;

$factory->define(App\Models\Post::class, function (Faker $faker) {
    return App\Models\Post::getRandomData();
});
