<?php declare(strict_types=1);
/**
 * This file is automatically generated by Modelarium on 2020-08-21T15:37:31+00:00.
 */

namespace App\Modelarium\Datatype\Types;

class Datatype_title extends \Modelarium\Types\FormulariumScalarType
{
}
