/**
 * This file was automatically generated by Modelarium
 * on 2020-08-27T14:18:18+00:00
 */

import * as components from "./index";

export default [
    {
        path: "/post",
        name: "PostList",
        component: components.PostList,
    },
    {
        path: "/post/:id?/edit",
        name: "PostEdit",
        component: components.PostEdit,
    },
    {
        path: "/post/table",
        name: "PostTable",
        component: components.PostTable,
    },
    {
        path: "/post/:id",
        name: "PostShow",
        component: components.PostShow,
    },
];
