<?php declare(strict_types=1);
/** 
 * This file was automatically generated by Modelarium on 2020-08-27T13:21:23+00:00
 */
namespace App\Models;

use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\Relations\MorphTo;
use Illuminate\Database\Eloquent\Relations\MorphToMany;
use Illuminate\Support\Facades\Auth;
use Modelarium\Laravel\Datatypes\Datatype_relationship;

/**
 * This file was automatically generated by Modelarium.
 */
abstract class BasePost extends \Illuminate\Database\Eloquent\Model
{
    /**
     * The attributes that are mass assignable.
     * @var array
     */
    protected $fillable = ['title', 'content', 'country'];

    /**
     * The attributes that should be hidden for arrays.
     * @var array
     */
    protected $hidden = [];

    /**
     * The attributes that should be cast to native types.
     * @var array
     */
    protected $casts = [];

    /**
     * @return array
     */
    public static function getFields(): array
    {
        return [
            'name' => 'Post',
            'renderable' => [],
            'extradata' => [['name' => 'migrationTimestamps', 'args' => []]],
            'fields' => [
                'title' => [
                    'datatype' => 'title',
                    'validators' => ['required' => ['value' => true]],
                    'renderable' => [
                        'title' => true,
                        'label' => 'Title',
                        'comment' => 'Please add a descriptive title',
                        'placeholder' => 'Type here',
                        'size' => 'large',
                        'card' => true,
                        'table' => true,
                    ],
                    'extradata' => [],
                ],
                'content' => [
                    'datatype' => 'text',
                    'validators' => ['required' => ['value' => true]],
                    'renderable' => ['label' => 'Content', 'comment' => 'Your post contents'],
                    'extradata' => [],
                ],
                'country' => [
                    'datatype' => 'countrycodeiso3',
                    'validators' => ['required' => ['value' => true]],
                    'renderable' => ['label' => 'Country', 'comment' => 'Pick a country', 'table' => true],
                    'extradata' => [],
                ],
            ],
        ];
    }

    /**
     * @return \Formularium\Model
     */
    public static function getFormularium(): \Formularium\Model
    {
        $model = \Formularium\Model::fromStruct(static::getFields());
        return $model;
    }

    /**
     * @return array
     */
    public static function getRandomData(): array
    {
        $data = static::getFormularium()->getRandom(get_called_class() . '::getRandomDataFilterFields');

        return $data;
    }

    /**
     * Filters fields used for random data generation.
     */
    public static function getRandomDataFilterFields(\Formularium\Field $f): bool
    {
        $d = $f->getDatatype();
        if ($d instanceof Datatype_relationship) {
            return false;
        }
        return true;
    }

    /**
     * Returns the policy permissions for actions such as editing or deleting.
     * @return \Formularium\Model
     */
    public function getCanAttribute(): array
    {
        $policy = new \App\Policies\PostPolicy();
        $user = Auth::user();
        return [
            //[ "ability" => "create", "value" => $policy->create($user) ]
        ];
    }
}
